/**
 * © Copyright IBM Corp. 2016, 2020 All Rights Reserved
 *   Project name: JSONata
 *   This project is licensed under the MIT License, see LICENSE
 */

export default {
  Metadata: {
    json: [
      {
        id: '17913de0-df49-11e6-93f3-0242c0a80605',
        code: null,
        xapiActivityId:
          'https://xapi.percipio.com/xapi/channel/17913de0-df49-11e6-93f3-0242c0a80605',
        xapiActivityTypeId: 'https://xapi.percipio.com/xapi/activity-type/channel',
        contentType: {
          percipioType: 'CHANNEL',
          category: 'CHANNEL',
          displayLabel: 'Channel',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Cloud Basics',
            description:
              '<p>Explore the core concepts of the Cloud, including the basics of cloud computing, why it&#39;s so popular, and where to begin.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2017-02-10T18:58:24Z',
          lastUpdatedDate: '2020-04-20T00:36:43Z',
        },
        link: 'https://share.percipio.com/cd/HJiKNsvTV2mV',
        imageUrl:
          'https://cdn2.percipio.com/public/c/channel/images/saved/17913de0-df49-11e6-93f3-0242c0a80605.jpg',
        keywords: [],
        duration: null,
        by: [],
        publication: null,
        credentials: null,
        expertiseLevels: [],
        modalities: [],
        technologies: [],
        associations: {
          areas: ['Cloud Services'],
          subjects: ['Cloud Basics'],
          channels: [],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: 'acb83870-e1a0-11e6-91a7-0242c0a80704',
        code: null,
        xapiActivityId:
          'https://xapi.percipio.com/xapi/channel/acb83870-e1a0-11e6-91a7-0242c0a80704',
        xapiActivityTypeId: 'https://xapi.percipio.com/xapi/activity-type/channel',
        contentType: {
          percipioType: 'CHANNEL',
          category: 'CHANNEL',
          displayLabel: 'Channel',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Software Testing',
            description:
              '<p>Software testing is a set of methodologies for ensuring the smooth operation and integrity of applications. Explore its various aspects here.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2017-03-24T12:50:59Z',
          lastUpdatedDate: '2020-04-20T00:40:02Z',
        },
        link: 'https://share.percipio.com/cd/rJEq7EO6EnmE',
        imageUrl:
          'https://cdn2.percipio.com/public/c/channel/images/saved/acb83870-e1a0-11e6-91a7-0242c0a80704.jpg',
        keywords: [],
        duration: null,
        by: [],
        publication: null,
        credentials: null,
        expertiseLevels: [],
        modalities: [],
        technologies: [],
        associations: {
          areas: ['Developer'],
          subjects: ['Developer Concepts & Methodologies'],
          channels: [],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '4550fd29-0e69-11e7-b952-0242c0a80b07',
        code: 'it_cscybs_01_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/4550fd29-0e69-11e7-b952-0242c0a80b07',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'CompTIA Cybersecurity Analyst+: Network Concepts',
            description:
              '<p>Existing IT system implementations must be understood before security controls can be recommended. Explore network concepts, including the OSI model, IPv4/IPv6, network ports, wired and wireless, and common tools.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2017-04-27T15:02:57Z',
          lastUpdatedDate: '2020-04-20T10:30:50Z',
        },
        link: 'https://share.percipio.com/cd/S1vkgdjRVhQN',
        imageUrl:
          'https://cdn2.percipio.com/public/b/fc5e6150-11c6-11e7-b952-0242c0a80b07/image001.jpg',
        keywords: [],
        duration: 'PT1H23M7S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cyber Security',
            version: null,
          },
        ],
        associations: {
          areas: ['CompTIA', 'IT Operations'],
          subjects: ['Cybersecurity', 'Information Security'],
          channels: [
            {
              id: 'f89fa5b1-2c1f-11e7-83d1-dba0327abefc',
              title: 'CompTIA CySA+',
              link: 'https://share.percipio.com/cd/HkSE7us0NnX4',
            },
            {
              id: '234e0060-e259-11e6-93f3-0242c0a80605',
              title: 'Cybersecurity',
              link: 'https://share.percipio.com/cd/r17pMgyRE2QV',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '7ca0b2d0-ce3e-11e7-845b-9d7d00b83945',
        code: 'bs_ldcldp_09_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/7ca0b2d0-ce3e-11e7-845b-9d7d00b83945',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Leadership Insights on Leading Virtually',
            description:
              '<p>What does it take to lead effectively in a virtual environment? Find out which traditional principles still apply and which new principles will make a difference in team effectiveness—no matter how geographically dispersed team members are.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2018-01-22T22:17:24Z',
          lastUpdatedDate: '2020-04-18T18:04:05Z',
        },
        link: 'https://share.percipio.com/cd/Bk48-4ylS2m4',
        imageUrl:
          'https://cdn2.percipio.com/public/b/322693e4-a052-401c-a377-f2721b626155/image008.jpg',
        keywords: [],
        duration: 'PT22M52S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: [],
        modalities: ['WATCH'],
        technologies: [],
        associations: {
          areas: ['Management'],
          subjects: ['Business Strategy'],
          channels: [
            {
              id: 'e27c4b77-f05f-4781-8e1a-48926005796d',
              title: 'Business Continuity',
              link: 'https://share.percipio.com/cd/mmYKfRifKtm',
            },
          ],
          parent: null,
          translationGroupId: 'efb4c385-dadf-48e9-aa30-46421298c822',
        },
      },
      {
        id: '781556a3-15b0-4aaa-9409-42ae98d2b0f3',
        code: null,
        xapiActivityId: 'https://xapi.percipio.com/xapi/book/781556a3-15b0-4aaa-9409-42ae98d2b0f3',
        xapiActivityTypeId: 'https://xapi.percipio.com/xapi/activity-type/book',
        contentType: {
          percipioType: 'BOOK',
          category: 'BOOK',
          displayLabel: 'Book Summary',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Influence Without Authority, Second Edition',
            description:
              'Influence Without Authority, Second Edition explores methods for creating influence in the workplace, and the tools, approaches, barriers, and preparations you can take to be successful. In this Summary, we discuss the salient points of the book based on our interpretations of its content.',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-06-05T21:25:03Z',
          lastUpdatedDate: '2020-04-20T11:05:30Z',
        },
        link: 'https://share.percipio.com/cd/8RkPV3PuV',
        imageUrl:
          'https://cdn2.percipio.com/public/c/books/144756/cover-images/a9dd5e37-3c83-44bd-bbde-5fcaa836beef.png',
        keywords: [],
        duration: 'PT12M',
        by: ['Allan R. Cohen', 'David L. Bradford'],
        publication: {
          copyrightYear: 2019,
          isbn: '9780471463306',
          publisher: 'Skillsoft',
        },
        credentials: null,
        expertiseLevels: [],
        modalities: ['READ'],
        technologies: [],
        associations: {
          areas: [],
          subjects: [],
          channels: [],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '8968cb32-f569-485d-8bae-19495721e184',
        code: null,
        xapiActivityId:
          'https://xapi.percipio.com/xapi/audiobook/8968cb32-f569-485d-8bae-19495721e184',
        xapiActivityTypeId: 'https://xapi.percipio.com/xapi/activity-type/audiobook',
        contentType: {
          percipioType: 'AUDIOBOOK',
          category: 'AUDIOBOOK',
          displayLabel: 'Audiobook Summary',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Influence Without Authority, Second Edition',
            description:
              'Influence Without Authority, Second Edition explores methods for creating influence in the workplace, and the tools, approaches, barriers, and preparations you can take to be successful. In this Summary, we discuss the salient points of the book based on our interpretations of its content.',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-06-05T21:25:04Z',
          lastUpdatedDate: '2020-04-20T11:07:11Z',
        },
        link: 'https://share.percipio.com/cd/S5TX-9kd-eTi',
        imageUrl:
          'https://cdn2.percipio.com/public/c/books/10144756/cover-images/03a833f9-2d20-4aa9-b260-32da17ce8315.png',
        keywords: [],
        duration: 'PT24M53S',
        by: ['Allan R. Cohen', 'David L. Bradford'],
        publication: {
          copyrightYear: 2019,
          isbn: '9780471463306',
          publisher: 'Skillsoft',
        },
        credentials: null,
        expertiseLevels: [],
        modalities: ['LISTEN'],
        technologies: [],
        associations: {
          areas: [],
          subjects: [],
          channels: [],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '01072cea-06fb-4492-8f55-19fcda239c52',
        code: 'ds_msex365_20_frfr',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/01072cea-06fb-4492-8f55-19fcda239c52',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['fr-FR'],
        localizedMetadata: [
          {
            localeCode: 'fr-FR',
            title: 'Configurer les options et paramètres',
            description:
              '<p>Pour tirer le meilleur parti d&#39;Excel en l&#39;adaptant à vos propres besoins, vous verrez comment gérer votre compte, les services connectés et les compléments. Vous verrez également comment configurer les options de saisie, de modèle et de formule et même comment personnaliser l&#39;interface, le ruban et la barre d&#39;outils Accès rapide.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-09-19T13:13:03Z',
          lastUpdatedDate: '2020-04-20T10:04:26Z',
        },
        link: 'https://share.percipio.com/cd/oO9hubReYwnQ',
        imageUrl:
          'https://cdn2.percipio.com/public/b/6fd066ec-bf03-4724-a02d-f3ce68c52032/image001.jpg',
        keywords: [],
        duration: 'PT52M55S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Excel',
            version: 'Office 365 (Windows)',
          },
        ],
        associations: {
          areas: ['Productivity & Collaboration Tools'],
          subjects: ['Microsoft Office'],
          channels: [
            {
              id: '3356fb80-e248-11e6-91a7-0242c0a80704',
              title: 'Excel',
              link: 'https://share.percipio.com/cd/S1ldROpVhmE',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '4f448a53-f9d9-4659-9845-324d041dbfac',
        code: 'ds_msex365_19_frfr',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/4f448a53-f9d9-4659-9845-324d041dbfac',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['fr-FR'],
        localizedMetadata: [
          {
            localeCode: 'fr-FR',
            title: 'Excel Office 365 : Trouver et analyser des informations avec les formules',
            description:
              '<p>Il existe une grande variéte d&#39;outils qui sont utilisés pour retrouver, retourner et calculer des données dans Excel. Voyez comment retrouver des dates et ordonner des valeurs, retrouver, combiner et séparer des données disponibles, ainsi qu&#39;automatiser et simplifier des calculs en utilisant les outils de recherche et SOMMEPROD.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-10-29T12:27:40Z',
          lastUpdatedDate: '2020-04-20T10:02:11Z',
        },
        link: 'https://share.percipio.com/cd/kWBPYTXVneU3',
        imageUrl:
          'https://cdn2.percipio.com/public/b/57d7fc5a-ae8a-4e2d-9724-7214cc4d6d28/image001.jpg',
        keywords: [],
        duration: 'PT47M8S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Excel',
            version: 'Office 365 (Windows)',
          },
        ],
        associations: {
          areas: ['Productivity & Collaboration Tools'],
          subjects: ['Microsoft Office'],
          channels: [
            {
              id: '3356fb80-e248-11e6-91a7-0242c0a80704',
              title: 'Excel',
              link: 'https://share.percipio.com/cd/S1ldROpVhmE',
            },
          ],
          parent: null,
          translationGroupId: 'b028535d-8215-4a11-a2d2-a9be70bd71d2',
        },
      },
      {
        id: '8709b606-b4f3-4740-895e-2fd3076d34e3',
        code: 'ds_msex2019_19_frfr',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/8709b606-b4f3-4740-895e-2fd3076d34e3',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['fr-FR'],
        localizedMetadata: [
          {
            localeCode: 'fr-FR',
            title: 'Excel 2019 : Rechercher et analyser des informations avec des formules',
            description:
              '<p>De nombreux outils différents peuvent être utilisés pour extraire, renvoyer et calculer des données dans Excel. Récupérez des informations de date et des valeurs de classement, extrayez, associez et séparez des données, et automatisez et simplifiez des calculs avec des outils et SOMMEPROD.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-11-27T15:32:24Z',
          lastUpdatedDate: '2020-04-20T10:02:56Z',
        },
        link: 'https://share.percipio.com/cd/JzpFACt77obo',
        imageUrl:
          'https://cdn2.percipio.com/public/b/15fb8586-e350-4f2e-884f-35b45620550d/image001.jpg',
        keywords: [],
        duration: 'PT40M4S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Excel',
            version: '2019 (Windows)',
          },
        ],
        associations: {
          areas: ['Productivity & Collaboration Tools'],
          subjects: ['Microsoft Office'],
          channels: [
            {
              id: '3356fb80-e248-11e6-91a7-0242c0a80704',
              title: 'Excel',
              link: 'https://share.percipio.com/cd/S1ldROpVhmE',
            },
          ],
          parent: null,
          translationGroupId: '74628355-90ea-4794-b994-f394ed8e36c5',
        },
      },
      {
        id: 'a28b0255-ccbd-420c-80ce-309041ad75d1',
        code: 'ds_msex2019_20_frfr',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/a28b0255-ccbd-420c-80ce-309041ad75d1',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['fr-FR'],
        localizedMetadata: [
          {
            localeCode: 'fr-FR',
            title: 'Excel 2019 : Configurer les options et les paramètres',
            description:
              '<p>Exploitez mieux Excel en l&#39;adaptant à vos propres besoins. Gérez votre compte, vos services connectés et compléments, configurez les options de saisie, de modèle et de formule, et personnalisez l&#39;interface, le ruban et la barre d&#39;outils Accès rapide.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2019-11-28T14:02:32Z',
          lastUpdatedDate: '2020-04-20T10:03:39Z',
        },
        link: 'https://share.percipio.com/cd/VG5f4WnpzDVk',
        imageUrl:
          'https://cdn2.percipio.com/public/b/c7c7404f-f04d-4962-8e60-f3fcab154bce/image001.jpg',
        keywords: [],
        duration: 'PT39M9S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Excel',
            version: '2019 (Windows)',
          },
        ],
        associations: {
          areas: ['Productivity & Collaboration Tools'],
          subjects: ['Microsoft Office'],
          channels: [
            {
              id: '3356fb80-e248-11e6-91a7-0242c0a80704',
              title: 'Excel',
              link: 'https://share.percipio.com/cd/S1ldROpVhmE',
            },
          ],
          parent: null,
          translationGroupId: '65ccd501-203c-47e1-9a8e-6db5a6ca3c59',
        },
      },
      {
        id: '06e113c7-db50-4ea4-b62c-095afccf5a11',
        code: 'it_clihsmp_10_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/06e113c7-db50-4ea4-b62c-095afccf5a11',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Implementing a Hybrid and Secure Messaging Platform: Sharing',
            description:
              '<p>Exchange Online offers numerous features that allow calendar information to be shared with others in an Exchange organization. In addition to learning how to manage internal sharing in Exchange, you&#39;ll examine how to create and manage organization relationships that can be used to share information with external business partners. These topics will help prepare you for the MS-201 Implementing a Hybrid and Secure Messaging Platform certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-06T11:14:49Z',
          lastUpdatedDate: '2020-04-20T09:45:32Z',
        },
        link: 'https://share.percipio.com/cd/pOmTAGS_Bdw',
        imageUrl:
          'https://cdn2.percipio.com/public/c/course/images/saved/06e113c7-db50-4ea4-b62c-095afccf5a11/32a51302-2d79-4f37-a34a-98d57024fdef.jpg',
        keywords: [],
        duration: 'PT50M3S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Microsoft 365',
            version: '2020',
          },
        ],
        associations: {
          areas: ['Cloud Services', 'Microsoft'],
          subjects: ['Cloud Platforms', 'Microsoft 365 Certified Associate'],
          channels: [
            {
              id: '6ea16b11-161b-11e7-bf96-7fcd66e560cd',
              title: 'Microsoft 365 Administration',
              link: 'https://share.percipio.com/cd/BJYfwtTEhQN',
            },
            {
              id: 'a0fd8f65-a378-491f-b983-3bb34c102b50',
              title: 'Microsoft 365 Certified: Messaging Administrator Associate',
              link: 'https://share.percipio.com/cd/XkPom-MuICi',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '360a8d85-65e7-477d-ab7e-a9d72e7b1e54',
        code: 'it_clihsmp_11_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/360a8d85-65e7-477d-ab7e-a9d72e7b1e54',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title:
              'Implementing a Hybrid and Secure Messaging Platform: E-mail Address Policies and Workload Management',
            description:
              '<p>E-mail address policies in Exchange Server 2019 can help define rules used to create e-mail addresses for recipients. In this course, you’ll start by examining e-mail address policies. You’ll then explore considerations when implementing multiple e-mail address policies, as well as default e-mail policy properties. Next, you’ll see how to manage e-mail address policies using the EAC and apply/remove e-mail address policies to recipients. You’ll explore Managed Availability, workload management components, and user resource consumption. You’ll then learn how to use the Get-ThrottlingPolicy cmdlet to determine user throttling settings, the New-ThrottlingPolicy cmdlet to create a user throttling policy, and the Set-ThrottlingPolicyAssociation cmdlet to assign a policy to a user. Lastly, you&#39;ll examine the available scopes in custom throttling policies and coexistence environments. These topics will help prepare you for the MS-201 Implementing a Hybrid and Secure Messaging Platform certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-06T11:17:02Z',
          lastUpdatedDate: '2020-04-20T09:53:10Z',
        },
        link: 'https://share.percipio.com/cd/pn3akslsdYu',
        imageUrl:
          'https://cdn2.percipio.com/public/c/course/images/saved/360a8d85-65e7-477d-ab7e-a9d72e7b1e54/e524bf88-fa02-4a8d-ba5c-690985504597.jpg',
        keywords: [],
        duration: 'PT1H21M31S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Microsoft 365',
            version: '2020',
          },
        ],
        associations: {
          areas: ['Cloud Services', 'Microsoft'],
          subjects: ['Cloud Platforms', 'Microsoft 365 Certified Associate'],
          channels: [
            {
              id: '6ea16b11-161b-11e7-bf96-7fcd66e560cd',
              title: 'Microsoft 365 Administration',
              link: 'https://share.percipio.com/cd/BJYfwtTEhQN',
            },
            {
              id: 'a0fd8f65-a378-491f-b983-3bb34c102b50',
              title: 'Microsoft 365 Certified: Messaging Administrator Associate',
              link: 'https://share.percipio.com/cd/XkPom-MuICi',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '7ebc9117-708c-42ff-aae1-2df7211c1352',
        code: 'it_clazad2020_08_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/7ebc9117-708c-42ff-aae1-2df7211c1352',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Microsoft Azure Administrator: Managing Azure Network Solutions',
            description:
              '<p>Azure network resources need to be managed. In this course, you&#39;ll explore Azure network resources, Azure VNet peering, and Azure ExpressRoute. You’ll start by determining which Azure network configurations should be used, and how to use the portal, CLI, and PowerShell to manage VNets and subnets. You’ll then learn how to manage both network interfaces and IP address resources. Next, you’ll discover how to configure routing table entries, the purpose of peering Azure VNets, and how to enable Azure VNet peering. Lastly, you’ll troubleshoot network issues using both Network Performance Monitor and Network Watcher, examine how ExpressRoute provides dedicated private network links to Azure, and enable ExpressRoute. This course is one of a collection of courses that prepares learners for the AZ-104 Microsoft Azure Administrator certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-06T14:06:14Z',
          lastUpdatedDate: '2020-04-20T09:42:48Z',
        },
        link: 'https://share.percipio.com/cd/KgRkUXlRItH',
        imageUrl:
          'https://cdn2.percipio.com/public/c/course/images/saved/7ebc9117-708c-42ff-aae1-2df7211c1352/65d234ea-be26-4753-b274-9c60b87d07d0.jpg',
        keywords: [],
        duration: 'PT1H29M46S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Azure',
            version: '2020',
          },
        ],
        associations: {
          areas: ['Microsoft'],
          subjects: ['Microsoft Azure Certified Associate'],
          channels: [
            {
              id: 'cc1c9d7b-af9a-42b7-a727-d9988fe3c941',
              title: 'Microsoft Certified: Azure Administrator Associate',
              link: 'https://share.percipio.com/cd/mzZp-P05YX6V',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '5bc3cd09-b01d-4f6d-8772-bfd136137913',
        code: 'it_clazad2020_09_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/5bc3cd09-b01d-4f6d-8772-bfd136137913',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Microsoft Azure Administrator: Managing Azure DNS & Network Security',
            description:
              '<p>Explore the management of Azure DNS services and its benefits. In this course, you’ll examine how DNS name resolution works in Azure, how to use the portal, CLI, and PowerShell to create a DNS zone, and how to enable custom DNS servers for a VNet. You’ll then examine how network security groups control inbound and outbound traffic flow, how to manage network security groups, and how to perform security rule troubleshooting. Next, you’ll see how to configure both a point-to-site VPN and a site-to-site VPN, and examine the benefits of using Azure Virtual WAN. Finally, you’ll learn how security issues are addressed by using Azure Firewall and Azure Bastion, and how to deploy and manage both Azure Firewall and Azure Bastion. This course is one of a collection of courses that prepares learners for the AZ-104 Microsoft Azure Administrator certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-07T11:10:59Z',
          lastUpdatedDate: '2020-04-20T09:59:42Z',
        },
        link: 'https://share.percipio.com/cd/vo3iQYoZ115',
        imageUrl:
          'https://cdn2.percipio.com/public/c/course/images/saved/5bc3cd09-b01d-4f6d-8772-bfd136137913/4c3201ca-aee9-41a0-928b-e724f95b028d.jpg',
        keywords: [],
        duration: 'PT1H47M1S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Azure',
            version: '2020',
          },
        ],
        associations: {
          areas: ['Microsoft'],
          subjects: ['Microsoft Azure Certified Associate'],
          channels: [
            {
              id: 'cc1c9d7b-af9a-42b7-a727-d9988fe3c941',
              title: 'Microsoft Certified: Azure Administrator Associate',
              link: 'https://share.percipio.com/cd/mzZp-P05YX6V',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '9a552ec8-9162-476c-9344-7ef6cf999b61',
        code: 'it_ccdnatv_03_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/9a552ec8-9162-476c-9344-7ef6cf999b61',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'DEVASC: Working with Data Formats',
            description:
              '<p>In this course, you&#39;ll learn about data formats, including what they are used for and popular formats you may encounter. Specifically, you&#39;ll examine the characteristics and structure of the JSON, XML, and YAML data formats. This course can be used in preparation for the 200-901: DevNet Associate certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-08T19:04:15Z',
          lastUpdatedDate: '2020-04-20T09:58:21Z',
        },
        link: 'https://share.percipio.com/cd/5Nd-BfUDNyD',
        imageUrl:
          'https://cdn2.percipio.com/public/b/35c86294-6cba-4ff8-980f-e041d5908eac/image006.jpg',
        keywords: [],
        duration: 'PT57M55S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cisco',
            version: 'DEVASC',
          },
        ],
        associations: {
          areas: ['IT Operations'],
          subjects: ['Network Operations'],
          channels: [
            {
              id: '5a69dd71-59e3-4042-b949-88223180b494',
              title: 'Cisco DevNet',
              link: 'https://share.percipio.com/cd/dm1oX9J5Oxt',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '0ecb047b-929f-40b2-8790-16cc2d01107a',
        code: 'it_ccdnatv_05_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/0ecb047b-929f-40b2-8790-16cc2d01107a',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'DEVASC: Development Methodologies & Software Quality',
            description:
              '<p>In this course, you&#39;ll learn about choosing a development methodology and ensuring software quality. First, you&#39;ll examine considerations when deciding to employ Agile, Lean, or Waterfall for software projects. Then you&#39;ll move on to explore considerations for software quality, including tools you can use to ensure your software projects meet requirements. This course can be used in preparation for the 200-901: DevNet Associate certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-08T19:10:54Z',
          lastUpdatedDate: '2020-04-20T09:56:07Z',
        },
        link: 'https://share.percipio.com/cd/4LSjY1EkMj-',
        imageUrl:
          'https://cdn2.percipio.com/public/b/23f5505c-5e42-4600-b6e8-e96513394426/image001.jpg',
        keywords: [],
        duration: 'PT29M12S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cisco',
            version: 'DEVASC',
          },
        ],
        associations: {
          areas: ['IT Operations'],
          subjects: ['Network Operations'],
          channels: [
            {
              id: '5a69dd71-59e3-4042-b949-88223180b494',
              title: 'Cisco DevNet',
              link: 'https://share.percipio.com/cd/dm1oX9J5Oxt',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '303dbc0a-2625-413b-9673-16bf305dfc8c',
        code: 'ds_msex2019_22_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/303dbc0a-2625-413b-9673-16bf305dfc8c',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'Excel 2019: Getting to Know Macros in Excel',
            description:
              '<p>If you have tasks in Excel 2019 that you do repeatedly, you can record a macro to automate those tasks. A macro is an action or a set of actions that you can run as many times as you want. When you create a macro, you are recording your mouse clicks and keystrokes.</p> <p>After you create a macro, you can edit it to make minor changes to the way it works. Macros and VBA tools can be found on the Developer tab, which is hidden by default, so the first step is to enable it. Once enabled, you&#39;ll be able to locate the VBA Editor as well as other key tools for managing macros in Excel.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-09T10:54:34Z',
          lastUpdatedDate: '2020-04-20T09:51:01Z',
        },
        link: 'https://share.percipio.com/cd/QqDU5FJ5nzB',
        imageUrl:
          'https://cdn2.percipio.com/public/b/43bbe691-70b8-401b-9e93-79bf0e3b2821/image001.jpg',
        keywords: [],
        duration: 'PT34M13S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['EXPERT'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Excel',
            version: '2019 (Windows)',
          },
        ],
        associations: {
          areas: ['Productivity & Collaboration Tools'],
          subjects: ['Microsoft Office'],
          channels: [
            {
              id: '3356fb80-e248-11e6-91a7-0242c0a80704',
              title: 'Excel',
              link: 'https://share.percipio.com/cd/S1ldROpVhmE',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '4b5b87ac-8028-4a7a-9ce4-d0a35a8e1fcc',
        code: 'it_ccdnatv_02_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/4b5b87ac-8028-4a7a-9ce4-d0a35a8e1fcc',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'DEVASC: Setting up Development & Virtualization Tools in Windows',
            description:
              '<p>In this course, you&#39;ll learn how to set up development and virtualization tools in Windows. First, you&#39;ll examine how to set up development tools such as Python, Git, Visual Studio Code, and Postman. Then, you&#39;ll move on to learn how to set up virtualization tools such as Vagrant, VirtualBox, and Docker. This course can be used in preparation for the 200-901: DevNet Associate certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-09T16:04:51Z',
          lastUpdatedDate: '2020-04-20T09:44:11Z',
        },
        link: 'https://share.percipio.com/cd/yNGdqj5f86p',
        imageUrl:
          'https://cdn2.percipio.com/public/b/2888e9b4-c8e3-4888-91ec-ebf26e377584/image003.jpg',
        keywords: [],
        duration: 'PT36M52S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cisco',
            version: 'DEVASC',
          },
        ],
        associations: {
          areas: ['IT Operations'],
          subjects: ['Network Operations'],
          channels: [
            {
              id: '5a69dd71-59e3-4042-b949-88223180b494',
              title: 'Cisco DevNet',
              link: 'https://share.percipio.com/cd/dm1oX9J5Oxt',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: '0835a6ce-2dfe-404a-9cf2-8b674a8e4cf5',
        code: 'it_ccdnatv_06_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/0835a6ce-2dfe-404a-9cf2-8b674a8e4cf5',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'DEVASC: Code Organization, Design Patterns, & Version Control',
            description:
              '<p>In this course, you&#39;ll learn about code organization, design patterns, and version control. First, you&#39;ll examine common practices for code organization, including examples in GitHub, Python, Go, and C&#43;&#43;. Next, you&#39;ll move on to explore common design patterns, such as the Model-View-Controller and Observer patterns. Finally, you&#39;ll delve into how you can use version control to record the state of software elements at certain points in time. This course can be used in preparation for the 200-901: DevNet Associate certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-09T16:44:32Z',
          lastUpdatedDate: '2020-04-20T09:49:37Z',
        },
        link: 'https://share.percipio.com/cd/AwvxFsEOHM_',
        imageUrl:
          'https://cdn2.percipio.com/public/b/3e87cf1d-cf15-4a52-b995-9b2c98bbc529/image001.jpg',
        keywords: [],
        duration: 'PT51M21S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cisco',
            version: 'DEVASC',
          },
        ],
        associations: {
          areas: ['IT Operations'],
          subjects: ['Network Operations'],
          channels: [
            {
              id: '5a69dd71-59e3-4042-b949-88223180b494',
              title: 'Cisco DevNet',
              link: 'https://share.percipio.com/cd/dm1oX9J5Oxt',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: 'bfbe578a-686f-4859-bafb-afe9b78c916f',
        code: 'it_ccdnatv_08_enus',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/bfbe578a-686f-4859-bafb-afe9b78c916f',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['en-US'],
        localizedMetadata: [
          {
            localeCode: 'en-US',
            title: 'DEVASC: HTTP, APIs, & Webhooks',
            description:
              '<p>In this course, you&#39;ll learn about HTTP, HTTP response codes, APIs, and webhooks. First, you&#39;ll examine HTTP fundamentals and standard uses. Then, you&#39;ll move on to explore HTTP codes, what they are used for, and what they represent. You&#39;ll also learn about the various types of application programming interfaces that are available. Finally, you&#39;ll discover the some of the uses of webhooks using an example in the Cisco platform. This course can be used in preparation for the 200-901: DevNet Associate certification exam.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-09T16:45:29Z',
          lastUpdatedDate: '2020-04-20T09:52:07Z',
        },
        link: 'https://share.percipio.com/cd/vnpw1m8rhK6',
        imageUrl:
          'https://cdn2.percipio.com/public/b/0b05dd33-2e89-46c9-a7c2-f453c114c62e/image001.jpg',
        keywords: [],
        duration: 'PT59M29S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'Cisco',
            version: 'DEVASC',
          },
        ],
        associations: {
          areas: ['IT Operations'],
          subjects: ['Network Operations'],
          channels: [
            {
              id: '5a69dd71-59e3-4042-b949-88223180b494',
              title: 'Cisco DevNet',
              link: 'https://share.percipio.com/cd/dm1oX9J5Oxt',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
      {
        id: 'e5af7cc2-7f43-4efe-85de-f495d176ed6a',
        code: 'ds_jiracld_04_frfr',
        xapiActivityId:
          'https://xapi.percipio.com/xapi/course/e5af7cc2-7f43-4efe-85de-f495d176ed6a',
        xapiActivityTypeId: 'http://adlnet.gov/expapi/activities/course',
        contentType: {
          percipioType: 'COURSE',
          category: 'COURSE',
          displayLabel: 'Course',
          source: null,
        },
        localeCodes: ['fr-FR'],
        localizedMetadata: [
          {
            localeCode: 'fr-FR',
            title: 'JIRA Cloud : Création de rapports dans Jira Software',
            description:
              '<p>Pour garder un œil sur les performances de votre projet, vous pouvez générer des rapports. Les rapports vous donnent une représentation visuelle des tickets de votre projet.</p> <p>Vous pouvez créer des rapports Jira pour les sprints, les versions, les tickets créés ainsi que les tickets résolus. Découvrez comment accéder à la fonction de rapports et choisissez le rapport dont vous avez besoin pour analyser les données de vos projets rapidement et clairement.</p>',
          },
        ],
        lifecycle: {
          status: 'ACTIVE',
          publishDate: '2020-04-17T12:18:00Z',
          lastUpdatedDate: '2020-04-20T10:00:59Z',
        },
        link: 'https://share.percipio.com/cd/nczNR0iyS2oXD',
        imageUrl:
          'https://cdn2.percipio.com/public/b/815a658c-f00a-4996-88ba-7b1b116d1826/image001.jpg',
        keywords: [],
        duration: 'PT38M17S',
        by: [],
        publication: null,
        credentials: {
          cpeCredits: null,
          nasbaReady: false,
          pduCredits: null,
        },
        expertiseLevels: ['INTERMEDIATE'],
        modalities: ['WATCH'],
        technologies: [
          {
            title: 'JIRA',
            version: 'Cloud',
          },
        ],
        associations: {
          areas: ['Developer', 'Productivity & Collaboration Tools'],
          subjects: ['Developer Tools', 'Productivity Tools'],
          channels: [
            {
              id: '1493dff1-1a2f-11e7-aa4b-c7a8e598b690',
              title: 'JIRA',
              link: 'https://share.percipio.com/cd/HJRpBImkSnXN',
            },
          ],
          parent: null,
          translationGroupId: null,
        },
      },
    ],
    jsonata: `$.(
      $comment := '*******************************************************';
      $comment := '*******************************************************';
      $comment := 'Example using Percipio Library Functions:';
      $comment := 'To generate plaintext and Extended Descriptions/Titles';
      $comment := 'and shorten values';
      $comment := '*******************************************************';
      $comment := '*******************************************************';
      
      $maxtitlelength := 30;
      $maxdescriptionlength := 100;

      $.{
            'assetid': id,
            'title': localizedMetadata[0].title ? localizedMetadata[0].title : '',
            'extendedTitle': localizedMetadata[0].title ? $extendedTitle(localizedMetadata[0].title,$) : '',
            'description': localizedMetadata[0].description ? localizedMetadata[0].description : '',
            'plainDescription': localizedMetadata[0].description ? $plainString(localizedMetadata[0].description,$maxdescriptionlength) : '',
            'extendedDescription': localizedMetadata[0].description ? $sabaDescription('USE_EXTENDED_DESCRIPTION',$) : '',
            'localeLanguage': $localeLanguage(localeCodes[0]),
            'contentType' : $getContentType($),
            'durationInHours': $isoDurationToHours(duration),
            'durationInMinutes': $isoDurationToMinutes(duration),
            'durationInSeconds': $isoDurationToSeconds(duration),
            'durationInMilliSeconds': $isoDurationToMillis(duration),
            'sabaKeywords': $sabaKeywordsArray($)
      }
  )`,
    baseconfig: {},
    customerconfig: {},
  },
  LearnerActivity: {
    json: [
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '083bbcf0-fbe7-11e8-9fd5-5576a1d5a483',
        contentId: 'bs_ldcdt_02_enus_01',
        contentTitle: 'Develop a Healthy Obsession with Technology',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-16T00:00:00Z',
        duration: '184',
        firstAccess: '2019-04-16T12:05:44.000Z',
        lastAccess: '2019-04-16T12:09:03.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '97%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'deee9b60-f268-11e8-a3f0-07dcf0c94ea9',
        contentId: 'bs_ldcme_01_enus_21',
        contentTitle: 'The Biggest Challenge for Executives: How to Receive and Get Coaching',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '357',
        firstAccess: '2019-04-15T15:27:57.000Z',
        lastAccess: '2019-04-15T20:28:01.000Z',
        totalAccess: '3',
        '% ofVideoOrBook': '67%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'cfb70a95-e7c2-11e6-88ea-0242c0a80c07',
        contentId: 'ds_msex2016_012_enus_01',
        contentTitle: 'Creating a PivotTable',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '468',
        firstAccess: '2019-04-15T15:30:31.000Z',
        lastAccess: '2019-04-15T20:10:06.000Z',
        totalAccess: '2',
        '% ofVideoOrBook': '99%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd64-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus',
        contentTitle: 'Expert Insights on Coaching',
        contentType: 'Course',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '3694',
        firstAccess: '2019-04-14T22:04:22.000Z',
        lastAccess: '2019-04-15T20:08:01.000Z',
        totalAccess: '30',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'df4fce30-f268-11e8-a3f0-07dcf0c94ea9',
        contentId: 'bs_ldcme_01_enus_22',
        contentTitle:
          'The Three Tools A Senior Leader Must Use: Self-Disclosure; Inquiry and Listening',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '82',
        firstAccess: '2019-04-15T15:30:54.000Z',
        lastAccess: '2019-04-15T15:33:01.000Z',
        totalAccess: '2',
        '% ofVideoOrBook': '48%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'dea906e0-f268-11e8-a3f0-07dcf0c94ea9',
        contentId: 'bs_ldcme_01_enus_20',
        contentTitle: "If You're Not Getting Better; You're Getting Worse",
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '177',
        firstAccess: '2019-04-15T15:24:57.000Z',
        lastAccess: '2019-04-15T15:27:56.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '55%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'de547e40-f268-11e8-a3f0-07dcf0c94ea9',
        contentId: 'bs_ldcme_01_enus_19',
        contentTitle: 'Feedback That Can Have the Biggest Impact',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '77',
        firstAccess: '2019-04-15T15:23:39.000Z',
        lastAccess: '2019-04-15T15:24:57.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '100%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'a27d97d0-b2fd-11e8-9fae-49e6b0e402f4',
        contentId: 'bs_ldcme_01_enus_18',
        contentTitle: 'Coaching Skills Fundamentals',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '252',
        firstAccess: '2019-04-15T15:19:21.000Z',
        lastAccess: '2019-04-15T15:23:39.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '83%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'fe89e920-d9d2-11e7-976f-4f5e51ac27e4',
        contentId: 'bs_ldcme_01_enus_17',
        contentTitle: 'Coaching a Bad Attitude',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '298',
        firstAccess: '2019-04-15T01:01:32.000Z',
        lastAccess: '2019-04-15T15:19:21.000Z',
        totalAccess: '3',
        '% ofVideoOrBook': '100%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'fe122110-d9d2-11e7-976f-4f5e51ac27e4',
        contentId: 'bs_ldcme_01_enus_16',
        contentTitle: 'Be a Better Coach',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '201',
        firstAccess: '2019-04-15T00:58:06.000Z',
        lastAccess: '2019-04-15T01:01:32.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '90%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'fdc90a20-d9d2-11e7-976f-4f5e51ac27e4',
        contentId: 'bs_ldcme_01_enus_15',
        contentTitle: 'Coaching Across Distance',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '210',
        firstAccess: '2019-04-15T00:54:31.000Z',
        lastAccess: '2019-04-15T00:58:06.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '99%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: 'fd6edc30-d9d2-11e7-976f-4f5e51ac27e4',
        contentId: 'bs_ldcme_01_enus_14',
        contentTitle: 'The Differences Between Mentoring and Coaching',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '152',
        firstAccess: '2019-04-15T00:51:55.000Z',
        lastAccess: '2019-04-15T00:54:31.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '98%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '13216a40-1e0b-11e7-a818-0242c0a80806',
        contentId: 'bs_ldcme_01_enus_13',
        contentTitle: 'Job One, Two & Three of Developing Your People',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '120',
        firstAccess: '2019-04-15T00:43:58.000Z',
        lastAccess: '2019-04-15T00:51:55.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '100%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '13214330-1e0b-11e7-a818-0242c0a80806',
        contentId: 'bs_ldcme_01_enus_12',
        contentTitle: "Great Coaching: Don't Give the Answer",
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '103',
        firstAccess: '2019-04-15T00:42:09.000Z',
        lastAccess: '2019-04-15T00:43:58.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '99%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd79-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_11',
        contentTitle: "Great Coaches Don't Have Answers",
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-15T00:00:00Z',
        duration: '169',
        firstAccess: '2019-04-14T22:29:45.000Z',
        lastAccess: '2019-04-15T00:42:10.000Z',
        totalAccess: '2',
        '% ofVideoOrBook': '100%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd77-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_10',
        contentTitle: "'People Team' Coaches",
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '174',
        firstAccess: '2019-04-14T22:26:46.000Z',
        lastAccess: '2019-04-14T22:29:44.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '90%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd75-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_09',
        contentTitle: 'Coaching Team Members',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '146',
        firstAccess: '2019-04-14T22:24:16.000Z',
        lastAccess: '2019-04-14T22:26:46.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '61%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd73-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_08',
        contentTitle: 'Effective Coaching',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '87',
        firstAccess: '2019-04-14T22:22:44.000Z',
        lastAccess: '2019-04-14T22:24:16.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '93%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd71-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_07',
        contentTitle: 'Coaches Build Self Confidence',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '185',
        firstAccess: '2019-04-14T22:19:35.000Z',
        lastAccess: '2019-04-14T22:22:44.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '98%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd6f-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_06',
        contentTitle: 'Good Coaches Ask Questions',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '139',
        firstAccess: '2019-04-14T22:17:11.000Z',
        lastAccess: '2019-04-14T22:19:35.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '62%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd6d-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_05',
        contentTitle: 'Six Question Coaching Process',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '229',
        firstAccess: '2019-04-14T22:13:20.000Z',
        lastAccess: '2019-04-14T22:17:11.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '98%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd6b-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_04',
        contentTitle: 'Coaching Your Team Members',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '82',
        firstAccess: '2019-04-14T22:08:57.000Z',
        lastAccess: '2019-04-14T22:13:20.000Z',
        totalAccess: '2',
        '% ofVideoOrBook': '50%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd69-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_03',
        contentTitle: 'How to Be a Better Coach',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '210',
        firstAccess: '2019-04-14T22:08:32.000Z',
        lastAccess: '2019-04-14T22:11:54.000Z',
        totalAccess: '2',
        '% ofVideoOrBook': '99%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd67-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_02',
        contentTitle: 'Tips on Coaching',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '146',
        firstAccess: '2019-04-14T22:06:05.000Z',
        lastAccess: '2019-04-14T22:08:32.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '95%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '270dcd65-05cd-11e7-b6c3-0242c0a80802',
        contentId: 'bs_ldcme_01_enus_01',
        contentTitle: 'Coaching: What Gets You 90% There',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '98',
        firstAccess: '2019-04-14T22:04:22.000Z',
        lastAccess: '2019-04-14T22:06:05.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '64%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '17d41970-a064-11e8-8b10-010aa9cfd76a',
        contentId: 'bs_amg09_a02_enus_01',
        contentTitle: 'Keeping Your Coachee Committed and Accountable',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-14T00:00:00Z',
        duration: '20',
        firstAccess: '2019-04-14T22:03:43.000Z',
        lastAccess: '2019-04-14T22:04:15.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '50%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
      {
        userId: 'olivertwist',
        firstName: 'Oliver',
        lastName: 'Twist',
        audience: 'All Users',
        contentUuid: '45514b4b-0e69-11e7-b952-0242c0a80b07',
        contentId: 'it_cscybs_02_enus_03',
        contentTitle: 'Virtualization',
        contentType: 'Video',
        status: 'Completed',
        completedDate: '2019-04-11T00:00:00Z',
        duration: '317',
        firstAccess: '2019-04-11T12:49:24.000Z',
        lastAccess: '2019-04-11T12:54:42.000Z',
        totalAccess: '1',
        '% ofVideoOrBook': '94%',
        emailAddress: 'oliver.twist@charlesdickens.co.uk',
        languageCode: 'English',
      },
    ],
    jsonata: `$.(
      $comment := '*******************************************************';
      $comment := '*******************************************************';
      $comment := 'Example using Percipio Library Functions:';
      $comment := 'To generate xAPIActivityId and format the duration';
      $comment := '*******************************************************';
      $comment := '*******************************************************';
  
      $.{
          'username': userId,
          'assetid': contentUuid,
          'xapiactivityid': $generateXapiIdForCompletions($),
          'duration_hhmmss': $wbtDuration(duration),    
          'status': (
              $coursestatus := $lookup([{
              'started': 'INCOMPLETE',
              'completed': 'COMPLETE'
              }
              ], ($lowercase(status))); $coursestatus ? $coursestatus : 'INCOMPLETE'
          ),
          'firstaccessdate': firstAccess ? firstAccess : null,
          'lastaccessdate': lastAccess ? lastAccess : null,
          'completeddate': completedDate ? completedData : null,
          'firstscore': firstScore ? $number(firstScore) : null,
          'lastscore': lastScore ? $number(lastScore) : null,
          'highscore': highScore ? $number(highScore) : null,
          'accessCount': totalAccess ? $number(totalAccess) : null
      }
  )`,
    baseconfig: {},
    customerconfig: {},
  },
};
